name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # آپدیت شد به v4

      - name: Setup Java
        uses: actions/setup-java@v4 # آپدیت شد به v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # نسخه‌ای پایدار و مطمئن

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --target-platform android-arm64

      - name: Upload APK
        uses: actions/upload-artifact@v4 # رفع ارور با آپدیت به v4
        with:
          name: my-calculator-app
          path: build/app/outputs/flutter-apk/*.apk
